# Generated by Django 3.1.5 on 2021-02-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_options_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='check',
        ),
    ]
